default_language_version:
  python: python3.7
default_stages: [commit]

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort --profile black
        language: python
        types: [python]

      - id: black
        name: black
        args: [--line-length=119]
        entry: poetry run black
        language: python
        types: [python]
        
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: python
        types: [python]
        
